"""Local HTML run reports — no extra dependencies."""

from __future__ import annotations

import html
from pathlib import Path

from readyagents.workflow.state import RunState


def render_html(state: RunState) -> str:
    rows = []
    for result in state.results:
        preview = result.error or result.output
        cost = result.usage.get("cost_micros") if result.usage else None
        cost_cell = "—" if cost is None else str(cost)
        rows.append(
            "<tr>"
            f"<td><code>{html.escape(result.node_id)}</code></td>"
            f"<td>{html.escape(result.type)}</td>"
            f"<td class='st-{html.escape(result.status)}'>{html.escape(result.status)}</td>"
            f"<td><pre>{html.escape(_preview(preview))}</pre></td>"
            f"<td>{result.attempts}</td>"
            f"<td>{html.escape(cost_cell)}</td>"
            "</tr>"
        )
    usage = ", ".join(f"{html.escape(k)}={v}" for k, v in state.usage.items()) or "—"
    spend = state.metadata.get("spend") if isinstance(state.metadata, dict) else None
    cache_line = "—"
    if isinstance(spend, dict):
        cache_line = (
            f"hits={spend.get('cache_hits', 0)} misses={spend.get('cache_misses', 0)} "
            f"savings_micros={spend.get('cache_savings_micros', 0)}"
        )
    elif state.usage.get("cache_hits") or state.usage.get("cache_savings_micros"):
        cache_line = (
            f"hits={state.usage.get('cache_hits', 0)} "
            f"misses={state.usage.get('cache_misses', 0)} "
            f"savings_micros={state.usage.get('cache_savings_micros', 0)}"
        )
    outputs = html.escape(_preview(state.output_keys or state.node_outputs, 4000))
    pending = html.escape(state.pending_node) if state.pending_node else "—"
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>Run {html.escape(state.run_id)} — {html.escape(state.status)}</title>
<style>
body {{ font-family: ui-sans-serif, system-ui, sans-serif; margin: 2rem; color: #111; }}
h1 {{ font-size: 1.25rem; }}
.meta {{ display: grid; grid-template-columns: 10rem 1fr; gap: .35rem 1rem; margin: 1rem 0 2rem; }}
.meta div.k {{ color: #555; }}
table {{ border-collapse: collapse; width: 100%; }}
th, td {{ border-bottom: 1px solid #ddd; text-align: left;
  padding: .45rem .4rem; vertical-align: top; }}
th {{ font-size: .8rem; text-transform: uppercase; color: #555; }}
pre {{ white-space: pre-wrap; margin: 0; font-size: .85rem; }}
.st-ok {{ color: #0a7; font-weight: 600; }}
.st-error {{ color: #c20; font-weight: 600; }}
.st-paused, .badge-paused {{ color: #b80; }}
.badge {{ display: inline-block; padding: .15rem .5rem; border-radius: 999px; background: #eee; }}
.badge-succeeded {{ background: #e6f7f0; color: #0a7; }}
.badge-failed {{ background: #fdeaea; color: #c20; }}
.badge-paused {{ background: #fff4d6; }}
footer {{ margin-top: 2rem; color: #777; font-size: .85rem; }}
</style>
</head>
<body>
<h1>ReadyAgents run <code>{html.escape(state.run_id)}</code>
<span class="badge badge-{html.escape(state.status)}">{html.escape(state.status)}</span></h1>
<div class="meta">
<div class="k">workflow</div><div>{html.escape(state.workflow_name)}</div>
<div class="k">started</div><div>{html.escape(state.started_at)}</div>
<div class="k">finished</div><div>{html.escape(str(state.finished_at or "—"))}</div>
<div class="k">pending_node</div><div>{pending}</div>
<div class="k">usage</div><div>{usage}</div>
<div class="k">cache</div><div>{html.escape(cache_line)}</div>
</div>
<h2>Timeline</h2>
<table>
<thead><tr><th>Node</th><th>Type</th><th>Status</th><th>Output</th><th>Attempts</th><th>cost_micros</th></tr></thead>
<tbody>
{"".join(rows) or '<tr><td colspan="6">No nodes recorded.</td></tr>'}
</tbody>
</table>
<h2>Outputs</h2>
<pre>{outputs}</pre>
<footer>Generated by ReadyAgents Core. Local report — not uploaded anywhere.</footer>
</body>
</html>
"""


def write_html_report(state: RunState, dest: Path) -> Path:
    dest = Path(dest)
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(render_html(state), encoding="utf-8")
    return dest


def _preview(value: object, limit: int = 800) -> str:
    text = value if isinstance(value, str) else repr(value)
    if len(text) > limit:
        return text[: limit - 1] + "…"
    return text
